---
- name: "Configurar interface ALSA Loopback: {{INSTALAR_SERVICO_JIBRI}}"
  lineinfile:
    dest: /etc/modprobe.d/alsa-loopback.conf
    state: "present"
    regexp: "^options snd-aloop enable=1,1,1,1,1 index=0,1,2,3,4"
    line: "options snd-aloop enable=1,1,1,1,1 index=0,1,2,3,4"
    create: yes
  when: INSTALAR_SERVICO_JIBRI

- name: "Carregar módulo kernel do snd-aloop: {{INSTALAR_SERVICO_JIBRI}}"
  modprobe:
    name: snd-aloop
    state: present
  when: INSTALAR_SERVICO_JIBRI

- name: Criar pasta de instalação e config
  file:
    path: "{{ INSTALACAO_PASTA }}"
    state: directory
    recurse: yes

- name: Copiar assets gráficos do serpro
  copy:
    src:  files/imagens
    dest: "{{ INSTALACAO_PASTA_WEB }}/"
  tags: assets_graficos
  when: INSTALAR_SERVICO_WEB | bool

- name: Copiar compose file
  template:
    src: opt/jitsi/{{item}}
    dest: "{{ INSTALACAO_PASTA }}/{{item}}"
  with_items:
    - docker-compose.yml
  tags: compose
  register: compose_file_status

- debug:
    msg:
      - Status do arquivo compose - {{compose_file_status.changed}}

- name: "Copiar arquivos do jibri: {{INSTALAR_SERVICO_JIBRI}}"
  template:
    src: opt/jitsi/jibri/{{item}}
    dest: "{{ INSTALACAO_PASTA_JIBRI }}/{{item}}"
  with_items:
    - ffmpeg-serpro
  when: INSTALAR_SERVICO_JIBRI | bool

- name: Copiar configuracao customizada do jitsi
  template:
    src: opt/jitsi/web/{{item}}
    dest: "{{ INSTALACAO_PASTA_WEB }}"
  with_items:
    - custom-config.js
    - interface_config.js
  register: reiniciar_stack

- name: Compose file mudou. Reconstruindo o stack
  shell: |
    docker-compose stop
    docker-compose rm -f
    docker-compose up -d
  args:
    chdir: "{{ INSTALACAO_PASTA }}/"
  when: compose_file_status.changed

- name: Reiniciar Stack
  shell: |
    docker-compose restart
  args:
    chdir: "{{ INSTALACAO_PASTA }}/"
  when: reiniciar_stack.changed
