---
- name: "Coletar informações sobre container {{container_nome}}"
  docker_container_info:
    name: "{{container_nome}}"
  register: stack_resultado

- name: "Iniciar stack se {{container_nome}} inexistente ou parado"
  shell: |
    docker-compose up -d
  args:
    chdir: "{{ INSTALACAO_PASTA }}/"
  when: (not stack_resultado.exists) or
        (stack_resultado.container['State']['Status'] != "running")
